export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_REBOTS_PENDING = 'REQUEST_REBOTS_PENDING';
export const REQUEST_REBOTS_SUCCESS = 'REQUEST_REBOTS_SUCCESS';
export const REQUEST_REBOTS_FAILED = 'REQUEST_REBOTS_FAILED';
